### ISSUE TITLE
Install CCI erroe

### ISSUE THREAD

**Issue by carlosvl** [SFDO-Tooling/homebrew-sfdo#28]
When I run 
brew install cumulusci

I get the following error:

==> Installing cumulusci from sfdo-tooling/sfdo
==> Downloading https://files.pythonhosted.org/packages/92/80/a81a8bf89263db947d8c715186b2e7f1754af263cd5fb391a8b8d490c5d5/cumulusci-2.4.3.tar.gz
Already downloaded: /Users/carlosvillalpando/Library/Caches/Homebrew/downloads/bbc48a9467aae9c8329e450ad8d8b3f3cf782bf711abdbfdcbb3aa9ea4d6b104--cumulusci-2.4.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6a/56/74dce1fdeeabbcc0a3fcf299115f6814bd9c39fc4161658b513240a75ea7/virtualenv-16.5.0.tar.gz
Already downloaded: /Users/carlosvillalpando/Library/Caches/Homebrew/downloads/9a59939e9c388b5f92812588c07ea8638b2862c0b88c7087cacbc22bf1053c24--virtualenv-16.5.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cumulusci/2.4.3/libexec --install-scripts=/usr/local/Cellar/cumulusci/2.4.3/libexec/bin --singl
Last 15 lines from /Users/carlosvillalpando/Library/Logs/Homebrew/cumulusci/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/cumulusci/2.4.3/libexec
--install-scripts=/usr/local/Cellar/cumulusci/2.4.3/libexec/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sfdo-tooling/homebrew-sfdo/issues

**Comment by jlantz** [comment]
Something got messed up in the Homebrew python environment.  The following commands should fix the issue:

```
brew postinstall python3
pip3 install setuptools
```
